IEEEWebsite/Models/Warning.cs
namespace IEEEWebsite.Models
{
    public class Warning
    {
            public int Id { get; set; }
            public string? UserName { get; set; }
            public string WarningName { get; set; }
            public string WarningReason { get; set; }

    }
}

IEEEWebsite/Controllers/WarningController.cs
using IEEEWebsite.Context;
using IEEEWebsite.Models;
using Microsoft.AspNetCore.Mvc;

namespace IEEEWebsite.Controllers
{
    public class WarningController : Controller
    {
        IEEEContext IEEEContext = new IEEEContext();
        public IActionResult ViewWarning()
        {
            var Warning = IEEEContext.Warnings.ToList();
            return View(Warning);
        }

        public IActionResult AddWarning()
        {
            var users = IEEEContext.Users.ToList();
            ViewBag.warning = users;
            return View();
        }
        public IActionResult SaveWarning(Warning newWarning)
        {
            var warning = IEEEContext.Warnings;
            warning.Add(newWarning);
            IEEEContext.SaveChanges();
            return RedirectToAction("ViewWarning");
        }

        /*Delete Warning*/
        public IActionResult DeleteWarning(int id)
        {
            var warnings = IEEEContext.Warnings.FirstOrDefault(x => x.Id == id);
            if (warnings != null)
            {
                IEEEContext.Warnings.Remove(warnings);
                IEEEContext.SaveChanges();
            }
            return RedirectToAction("ViewWarning");
        }
        public IActionResult UpdateWarning(int Id)
        {
            var currWarning = IEEEContext.Warnings.FirstOrDefault(x => x.Id == Id);
            var users = IEEEContext.Users.ToList();
            ViewBag.warning = users;
            return View("AddWarning", currWarning);

        }
        public IActionResult SaveUpdateWarning(Warning newWanring)
        {
            var currWarning = IEEEContext.Warnings.FirstOrDefault(x => x.Id == newWanring.Id);
            if (currWarning != null)
            {
                currWarning.WarningName = newWanring.WarningName;
                currWarning.WarningReason = newWanring.WarningReason;
                currWarning.UserName = newWanring.UserName;
                IEEEContext.SaveChanges();
            }
            return RedirectToAction("ViewWarning");
        }
    }
}

IEEEWebsite/Views/Warning/AddWarning.cshtml
@model Warning

@{
    ViewData["Title"] = "Add Warning";
}
@{
   
    var Action = Model == null? "SaveWarning": "SaveUpdateWarning";
    var txt = Model == null ? "Add Warning" : "Update Warning";


}

<form class="all-login" asp-action="@Action" asp-controller="Warning" asp-route-id="@Model?.Id">
    <div class="container">
        @*Notes*@
        <div class="Warning-Note">
            <div>
                <p class=" text-center">Make bold  </p>
                <div class="copylink">
                    <i class="fa-solid fa-copy  text-success"></i>    
                </div>
            </div>
            <div>
                <p class="text-center">Make italic   </p>
                <div class="copylink">
                    <i class="fa-solid fa-copy text-success"></i>    
                </div>
            </div>
             
        </div>


        @*Name *@
        <div class="mb-3">
            <label for="name" class="form-label">Warning Name</label>
            <input type="text" class="form-control" id="name"  placeholder="Warning Name"
            asp-for="WarningName" >
            <span asp-validation-for = "WarningName" class="text-danger"></span>
      </div>
      @*Description*@
      <div class="mb-3">
            <label for="description" class="form-label">Warning Description</label>
             <textarea class="form-control" placeholder="Warning Description" id="floatingTextarea"
             asp-for="WarningReason"></textarea>
            <span asp-validation-for = "WarningReason" class="text-danger"></span>
      </div>  

      @*CategoryName*@
        <div class="mb-3">
            <label  class="form-label">Category</label>
            <select class="form-select form-select-sm" aria-label=".form-select-sm example" asp-for="UserName">
                @{
                    foreach(var item in ViewBag.warning)
                    {     
                        <option value="@item.FName @item.LName" selected>@item.FName @item.LName</option>
                    }
                }
              
           </select>
        </div>
       

      @*Submit*@
      <button type="submit" class="btn">@txt</button>
  </div>
</form>

@section Scripts{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation//dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<script>
let btns = document.querySelectorAll(".Warning-Note div .copylink");
btns[0].addEventListener("click", () => {
    var textToCopy = "<b>Text Here</b>";
    copyToClipBoard(textToCopy);
  
})
btns[1].addEventListener("click", () => {
    var textToCopy = "<i>Text Here</i>";
    copyToClipBoard(textToCopy);
  
})
function copyToClipBoard(textToCopy) 
{
    //create a temp textarea 
     var tempTextArea = document.createElement("textarea");
    tempTextArea.value = textToCopy;
    document.body.appendChild(tempTextArea)
    tempTextArea.select()
    tempTextArea.setSelectionRange(0, 99999); // for phone
    document.execCommand("copy");
    //remove a textarea
     document.body.removeChild(tempTextArea);

}



</script>



<style>

    .all-login
    {
        padding-top:30px;
        padding-bottom:30px;
        display:flex;
        align-items:center;
        justify-content:center;
        min-height:80vh;
        background-color:#f3f0f0;
    }
    .all-login .container
    {
        width:min(500px, 94vw);
        background-color:#262424;
        padding:30px;
        border-radius:20px;
    }
    .Warning-Note
    {
       
        color:#6c757d;
    }
    .Warning-Note > div
    {
         display: flex;
        justify-content: space-around;
        width: min(400px, 94%);
        margin: auto;
    }
    .Warning-Note p
    {
        margin:0px;
    }
    .Warning-Note svg {
        cursor:pointer;
    }

    .all-login .container label
    {
        color:#eee !important;
    }
    button.btn
    {
        background-color:#636c6c;
        color:#f3ebeb;
    }
    button.btn:hover
    {
        background-color:white;
        transition:.4s;
    }


</style>

IEEEWebsite/Views/Warning/ViewWarning.cshtml
@using System.Text.RegularExpressions
@model List<Warning>



@{
    static string HandleDescription(string Description)
    {
        string urlPattern = @"(http|https|ftp)://[^\s/$.?#].[^\s]*";
        string finalText = "";
        var spiltNewLine = Description.Split("\n");
        foreach (var line in spiltNewLine)
        {
            string replacedText = Regex.Replace(line, urlPattern, match => {
                string url = match.Value;
                return $"<a href='{url}'>{url}</a>";
            });
            finalText += $"<p>{replacedText}</p>";

        }
        @*String Formating*@
        
        string codePattern = @"`(.*?)`";

        
        string codeReplacement = "<code>$1</code>";

        string result = Regex.Replace(finalText, codePattern, codeReplacement);


        return result;
    }
}
@{
    ViewData["Title"] = "Warning";
}


	
<div>
    <table class="table table-dark table-striped container mt-5 w-75">
        <div class="add-category">
	        <a asp-action="AddWarning" asp-controller="Warning">Add Warning</a>
        </div>
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Warning Name</th>
          <th scope="col">Warning Reason</th>
          <th scope="col">Warning Person</th>
          <th scope="col">Update Warning</th>
          <th scope="col">Delete Warning</th>
        </tr>
      </thead>
      <tbody>
            @{
                var cnt = 1;
                foreach(var item in Model)
                {      
                    <tr >
                      <th >@cnt</th>
                      <td >@item.WarningName</td>
                      <td >
                            @{
                                var Description = item.WarningReason;
                                var result = HandleDescription(Description);
                                
                            }
                            @Html.Raw(result)
                            </td>
                      <td>
                          @item.UserName
                      </td>
                      <td >
                           <a asp-action="UpdateWarning" asp-controller="Warning" asp-route-id="@item.Id"
                            class="text-success">
                                 <i class="fa-solid fa-pen-to-square"></i>
                           </a>
                      </td>
                      <td class="text-center">
                        <a asp-action="DeleteWarning" asp-controller="Warning" asp-route-id="@item.Id"
                         class="text-danger">
                            
                            <i class="fa-solid fa-trash"></i>
                        </a>
                      
                      </td>
                    </tr>
                    cnt++;
                }
            }
      
      </tbody>
    </table>
</div>

<style>
    td svg{
        cursor:pointer;
    }
    td, tr
    {
        text-align:center;
    }
    .add-category
    {
        background-color:#2c3034;
        width:fit-content;
        margin-left:auto;
        margin-right:auto;
        margin-top:40px;
        border-radius:10px;
        padding:20px;
        font-weight:500;
    }
    .add-category a
    {
        color:#fff;
        text-decoration:none;
    }
    .add-category:hover
    {
        background-color:#212529;
    }
    .add-category a:hover
    {
        color:#357ae8;
        font-weight:700;
    }
   

</style>